### PR TITLE
Fix issue 780

### LINKED ISSUE #780: DatasetSuite Failure
```
==> X lucuma.core.model.sequence.DatasetSuite.Dataset.Filename.FromString: Prism.round trip other way  0.017s munit.FailException: /home/runner/work/lucuma-core/lucuma-core/modules/tests/shared/src/test/scala/lucuma/core/model/sequence/DatasetSuite.scala:17
16:
17:  checkAll("Dataset.Filename.FromString", PrismTests(Dataset.Filename.FromString))
18:}

Failing seed: q3HHYrhN4K2hmW_85ylC2WB22ml0RIgoqPh-ui_-UfH=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "q3HHYrhN4K2hmW_85ylC2WB22ml0RIgoqPh-ui_-UfH="

Falsified after 53 passed tests.
> Labels of failing property: 
Expected Some(Filename(GS,0000-12-16,1701874008)) but got Some(Filename(GS,0001-12-16,1701874008))
> ARG_0: Filename(GS,0000-12-16,1701874008)
```

### PR DESCRIPTION
**Pull request by swalker2m**
Fixes #780.  Format pattern `yyyy` switches year 0 to year 1 for some very good reason.

### CODE REVIEW

File: modules/core/shared/src/main/scala/lucuma/core/model/sequence/Dataset.scala [hunk 1]
```diff
@@ -67,7 +67,7 @@ object Dataset {
       Option.when(localDate.getYear >= 0 && localDate.getYear <= 9999)(Filename(site, localDate, index))
 
     private val DateFormatter: DateTimeFormatter =
-      DateTimeFormatter.ofPattern("yyyyMMdd")
+      DateTimeFormatter.ofPattern("uuuuMMdd")
```
Comment (cquiroz) [inline modules/core/shared/src/main/scala/lucuma/core/model/sequence/Dataset.scala:70]: Uhh interesting, is this working on the js side of things?

Comment (swalker2m) [reply modules/core/shared/src/main/scala/lucuma/core/model/sequence/Dataset.scala:70]: Yes, now passes both JVM and JS.

**Review by cquiroz — APPROVED** [review]
LGTM
